feat/Add support for adding w3cHeader
Instabug/Instabug-Dart-http-Adapter pull request #21
Opened 2024-07-24 11:26 UTC by ahmedAlaaInstabug

## Description of the change
1)  add Support for w3cHeader
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Related issues

 JIRA ID: MOB-14532

### Development
- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
### Code review 
- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-08-20 07:59 UTC, a7medev requested changes
I feel like the code for getting the W3C header and populating it is duplicated throughout all the HTTP methods, can we refactor this somehow?

2024-08-20 07:59 UTC, a7medev commented on CHANGELOG.md
> +  header ([#21](https://github.com/Instabug/Instabug-Dart-http-Adapter/pull/21)).
I think something along these lines would be more meaningful to users?

```suggestion
- Add support for tracing network requests from Instabug to services like Datadog and New Relic ([#481](https://github.com/Instabug/Instabug-Flutter/pull/481)).
```

2024-11-06 07:50 UTC, a7medev approved these changes, later dismissed

2024-11-06 07:54 UTC, AndrewAminInstabug submitted a review, later dismissed

2024-11-18 14:28 UTC, mzelzoghbi approved these changes

2024-11-18 14:35 UTC, merged